### PR TITLE
Full width image article template

### PR DESCRIPTION
**Pull request by joshdarby**
## Changes

This pull request makes the following changes:

- Adds a new template for posts to use to display a full-width image header area with overlaid title and subtitle
- Increases post body font size to 20px/1.25rem

Desktop:
screencapture-calhealth-test-2020-05-19-this-crisis-has-led-to-more-equitable-policies-that-california-should-keep-2020-05-27-12_12_57

Mobile:
screencapture-calhealth-test-2020-05-19-this-crisis-has-led-to-more-equitable-policies-that-california-should-keep-2020-05-27-12_12_34

## Why

For #9

## Testing/Questions

Features that this PR affects:

- New full-width image template

Questions that need to be answered before merging:

- [x] Is this PR targeting the correct branch in this repository?
- [ ] Do we want to add in an opaque color overlay on the image? The title is sometimes hard to read, like in this example:
Screen Shot 2020-05-27 at 12 17 44 PM
- [ ] Most posts have the featured image in the post content but @MirandaEcho says not to worry about that and they'll take care of it on an individual basis while using this template https://github.com/INN/theme-calhealthreport/issues/9#issuecomment-632929569

Steps to test this PR:

1. Create/find a post and give it a featured image with a caption
2. Add in a title and subtitle
3. Select the new full width image template
4. View on frontend and make sure everything looks ok

### CODE REVIEW

**Comment by benlk** [comment]
> Do we want to add in an opaque color overlay on the image? The title is sometimes hard to read, like in this example:

I'd at least give the text a strong drop shadow.

Screen Shot 2020-05-27 at 18 42 39

Should we decrease the font size of the subtitle so it's more than 2px smaller than the title?

**Comment by benlk** [comment]
Also, are we worried about providing support for IE's nonstandard flexbox implementation?

**Comment by joshdarby** [comment]
> > Do we want to add in an opaque color overlay on the image? The title is sometimes hard to read, like in this example:
> 
> I'd at least give the text a strong drop shadow.
> 
> Screen Shot 2020-05-27 at 18 42 39
> 
> Should we decrease the font size of the subtitle so it's more than 2px smaller than the title?

@MirandaEcho What do you think about those two additions?
- text drop shadow
- decrease subtitle size

**Review by benlk — APPROVED** [review]
I guess we can do the drop-shadow bit in the next round of QA.

**Pull request merged**
